//! Deterministic core of Craft, ported 1:1 from the original C sources.
//!
//! Everything here is pure and platform-independent in logic; float results
//! are validated against golden fixtures generated by the C oracle (see the
//! `oracle/` directory and the parity tests in `tests/`).

pub mod config;
pub mod cube;
pub mod item;
pub mod map;
pub mod matrix;
pub mod mesh;
pub mod noise;
pub mod physics;
pub mod world;
